### ISSUE TITLE
Possible problems with sparkey files with two dots in file names.

### ISSUE THREAD

**Issue by eshwaran** [spotify/sparkey-java#21]
Say you have a Sparkey index file and log file that is in the following form:

a-b-c.sparkey.spi, a-b-c.sparkey.spl. Assuming the "base file" here is "a-b-c.sparkey", the getIndexFile method will return "a-b-c.spi" and the getLogFile method will return "a-b-c.spl"

**Comment by spkrka** [comment]
Good catch, that should be easy to fix!

**Comment by spkrka** [comment]
This would hopefully fix your issue: #22

**Comment by eshwaran** [comment]
Yes. Should I close the issue?
