### ISSUE TITLE
Allow direct closing of Sparkey Reader

### ISSUE THREAD

**Issue by bendahl** [spotify/sparkey-java#27]
We're currently using Sparkey in a way that requires us to use many large Sparkey files at once for a short period of time, with new files being opened at a (potentially) very high rate during peak times. 
This happens in a multi threaded context, with each reader being used from a separate thread. Readers are not shared between threads. During our performance tests we've occasionally had issues with virtual memory filling up and not being released quick enough, using up all virtual address space on the machine. It appears that this is largely due to the fact that the current implementation uses a fixed timeout of 1 second before the actual memory cleanup happens. I do understand the reasoning behind this after reading the following discussion: 
https://github.com/spotify/sparkey-java/pull/13.

However, my question is whether it would be an option to make this behavior configurable in the sense that it should be possible to choose whether a reader is closed immediately, instead of being closed using an executor and a timeout. If not explicitly disabled, the timeout would still apply. This way, the change should be downward compatible. 
Another option that comes to my mind is that it would be possible to pass a timeout value in the new constructor. If the timeout is 0, the closing of the file would happen immediately within the same thread, otherwise the timeout for the close action would simply be set to the given value and execution would happen in a separate thread (like today). Does this sound like a reasonable suggestion or am I missing anything?

**Comment by krka** [comment]
(I have commented a bit more on the pull request.)

I don't fully understand the use case here. Are you quickly opening multiple readers of different files or of the same file? If it's the latter, you could use reader.duplicate() to get a new reader that doesn't consume any additional file descriptors (it shares the underlying bytebuffers)

The way I would prefer to implement this is not with a timeout but with a cleaner-setting, such as you've already done in the pull request.

**Comment by bendahl** [comment]
Thanks for the reply! Both scenarios may occur, depending on requests coming in from our client. Most likely multiple files will be used, so we cannot always rely on reader.duplicate(), although this is a good hint.

The pull request would definitely solve the issue. Also, I do agree that this is a better solution, as opposed to the timeout. If we could get this integrated, that would be fantastic!
